### ISSUE TITLE
Crash while using cropnalyzer.

### ISSUE THREAD

**Issue by bedrill64** [TinyModularThings/IC2-Nei-Plugin#7] opened 2019-02-27 19:12 UTC
Not really sure what I've done, was just checking combinations of crops. Crashlog below.
[crash-2019-02-27_20.10.32-client.txt](https://github.com/TinyModularThings/IC2-Nei-Plugin/files/2911902/crash-2019-02-27_20.10.32-client.txt)

Edit. Recreated this crash, happened at the same action, while trying to check 2 oil berry breed results, 3rd oilberry appear in crop windows and then game crashes, second crashlog included.
[crash-2019-02-27_20.47.22-client.txt](https://github.com/TinyModularThings/IC2-Nei-Plugin/files/2912020/crash-2019-02-27_20.47.22-client.txt)

Happened 3rd time, this time no 3rd crop appearance, crashed while checking results of oilberries breed.
[crash-2019-02-27_21.34.43-client.txt](https://github.com/TinyModularThings/IC2-Nei-Plugin/files/2912212/crash-2019-02-27_21.34.43-client.txt)

And again, with different crop, iirc fertilia, seems to occur when checking results of given crosbreed too fast.
[crash-2019-02-27_22.15.40-client.txt](https://github.com/TinyModularThings/IC2-Nei-Plugin/files/2912340/crash-2019-02-27_22.15.40-client.txt)

Plugin version: IC2+Nei+Plugin+Version+1.7.10-1.2.1

**Comment by Speiger** [comment] 2019-02-28 06:46
ok these are all the same crash and i wonder why that is happening because this is a impossible crash with ic2exp alone. I can not reproduce this.
The only way this could be achieved if someone deletes all crops and adds less then 9 options to it.
Could you provide a screenshot of your ui (before the crash) @bedrill64 ?
Edit: a video would be better. So i can see exactly how you made this crash.

**Comment by bedrill64** [comment] 2019-02-28 20:30
I do not have software to create proper video, So, those 2 screens below are screens in which crash happened for me, as I move mouse cursor at results to check it game crashes with crashlogs I gave you above.

![2019-02-28_21 24 00](https://user-images.githubusercontent.com/9555787/53596394-ea677b80-3b9f-11e9-97d2-3c8f142dbed2.png)
![2019-02-28_21 24 28](https://user-images.githubusercontent.com/9555787/53596398-edfb0280-3b9f-11e9-943a-223f27302500.png)

**Comment by Speiger** [comment] 2019-03-01 07:45
ok thanks this actually explains why there is a crash, because i assume that the output should also have at least 9 crops if that is not given there is no wonder that it crashes...
will be fixed within the next 10-20 min as of writing this message

**Comment by Speiger** [comment] 2019-03-01 08:14
9 minutes late. But submitted

**Closed as completed by Speiger** 2019-03-01 08:14 UTC
